export const dailyCopy = {
  en: {
    viewPhoto: "View photo",
    upcomingClasses: "Upcoming classes",
    otherClasses: "Explore other classes",
    loading: "Loading…",
    courseUnavailable: "Course timetable unavailable.",
    next: "Next lesson",
    now: "In a lesson",
    free: "Available now",
    soon: "Lesson starting",
    until: "until",
    startsIn: "Starts in",
    availableIn: "Available in",
    noMore: "No more lessons today",
    unknown: "Timetable unavailable",
    private: "Timetable not shared",
    basedOn: "Based on the shared timetable",
    profile: "Open profile",
    close: "Close",
    synced: "Last synced",
    minutes: "min",
    hours: "h",
    teachers: "Teachers",
    teacherProfile: "CTU profile & contacts",
    teacherHint: "Office, email and other public details in Usermap.",
    capacity: "Occupancy / capacity",
    unavailable: "Not provided",
    sequence: "Lesson number",
    changes: "Schedule changes",
    original: "Previously",
    details: "Subject details",
    food: "Food",
    menus: "Menza menus",
    officialMenu: "Official menus",
    menuPending:
      "Menus are not connected yet. Today's meals are available on the official menza website.",
    menuError: "Menus are temporarily unavailable.",
    noMeals: "No menu published for today.",
    canteen: "Canteen",
    studentPrice: "CTU student",
    regularPrice: "Standard",
    allergens: "Allergens",
    openingHours: "Opening hours",
    closed: "Closed",
    open: "Open",
    today: "Today",
    retry: "Retry",
    updated: "Updated",
    foodSource: "Source: ČVUT SÚZ",
    todayOnly: "Today's menu",
    ukMenu: "Meal names are provided in English.",
  },
  cs: {
    viewPhoto: "Zobrazit fotku",
    upcomingClasses: "Příští hodiny",
    otherClasses: "Prozkoumat další paralelky",
    loading: "Načítání…",
    courseUnavailable: "Rozvrh předmětu není dostupný.",
    next: "Příští hodina",
    now: "Na hodině",
    free: "Teď má volno",
    soon: "Brzy začíná hodina",
    until: "do",
    startsIn: "Začíná za",
    availableIn: "Volno za",
    noMore: "Dnes už žádná hodina",
    unknown: "Rozvrh není dostupný",
    private: "Rozvrh není sdílený",
    basedOn: "Podle sdíleného rozvrhu",
    profile: "Otevřít profil",
    close: "Zavřít",
    synced: "Poslední synchronizace",
    minutes: "min",
    hours: "h",
    teachers: "Vyučující",
    teacherProfile: "Profil ČVUT a kontakty",
    teacherHint: "Kabinet, e-mail a další veřejné údaje v Usermapu.",
    capacity: "Obsazenost / kapacita",
    unavailable: "Není uvedeno",
    sequence: "Číslo hodiny",
    changes: "Změny rozvrhu",
    original: "Původně",
    details: "Podrobnosti předmětu",
    food: "Jídlo",
    menus: "Jídelníčky menz",
    officialMenu: "Oficiální jídelníčky",
    menuPending:
      "Jídelníčky zatím nejsou připojené. Dnešní nabídku najdete na webu menz.",
    menuError: "Jídelníčky jsou dočasně nedostupné.",
    noMeals: "Na dnešek není zveřejněný jídelníček.",
    canteen: "Menza",
    studentPrice: "Student ČVUT",
    regularPrice: "Základní",
    allergens: "Alergeny",
    openingHours: "Otevírací doba",
    closed: "Zavřeno",
    open: "Otevřeno",
    today: "Dnes",
    retry: "Zkusit znovu",
    updated: "Aktualizováno",
    foodSource: "Zdroj: ČVUT SÚZ",
    todayOnly: "Dnešní nabídka",
    ukMenu: "Názvy jídel jsou v angličtině.",
  },
  uk: {
    viewPhoto: "Переглянути фото",
    upcomingClasses: "Наступні заняття",
    otherClasses: "Переглянути інші групи",
    loading: "Завантаження…",
    courseUnavailable: "Розклад предмета недоступний.",
    next: "Наступне заняття",
    now: "На занятті",
    free: "Зараз вільний час",
    soon: "Заняття незабаром",
    until: "до",
    startsIn: "Початок через",
    availableIn: "Вільний час через",
    noMore: "Сьогодні занять більше немає",
    unknown: "Розклад недоступний",
    private: "Розклад не надано",
    basedOn: "За спільним розкладом",
    profile: "Відкрити профіль",
    close: "Закрити",
    synced: "Остання синхронізація",
    minutes: "хв",
    hours: "год",
    teachers: "Викладачі",
    teacherProfile: "Профіль ЧВУТ та контакти",
    teacherHint: "Кабінет, електронна пошта та інші публічні дані в Usermap.",
    capacity: "Заповненість / місткість",
    unavailable: "Не вказано",
    sequence: "Номер заняття",
    changes: "Зміни розкладу",
    original: "Раніше",
    details: "Деталі предмета",
    food: "Їжа",
    menus: "Меню їдалень",
    officialMenu: "Офіційні меню",
    menuPending:
      "Меню ще не підключено. Сьогоднішні страви доступні на офіційному сайті їдалень.",
    menuError: "Меню тимчасово недоступні.",
    noMeals: "На сьогодні меню не опубліковано.",
    canteen: "Їдальня",
    studentPrice: "Студент ЧВУТ",
    regularPrice: "Звичайна",
    allergens: "Алергени",
    openingHours: "Години роботи",
    closed: "Зачинено",
    open: "Відчинено",
    today: "Сьогодні",
    retry: "Спробувати знову",
    updated: "Оновлено",
    foodSource: "Джерело: ЧВУТ SÚZ",
    todayOnly: "Меню на сьогодні",
    ukMenu: "Назви страв надано англійською.",
  },
};
