export const subjectCopy = {
  en: {
    subjects: "Subjects",
    intro: "Your own space for notes and tasks, one subject at a time.",
    private:
      "Only you can see these notes and tasks, even when you share your timetable.",
    subject: "Subject",
    empty:
      "No subjects yet. Sync your timetable or add a personal subject to get started.",
    notes: "Notes",
    notesHint: "Lecture notes, useful links, or things to remember…",
    saveNotes: "Save notes",
    tasks: "Tasks",
    todo: "To do",
    doing: "In progress",
    done: "Done",
    add: "Add task",
    edit: "Edit task",
    title: "Task title",
    description: "Description",
    due: "Due date",
    checklist: "Checklist",
    addItem: "Add checklist item",
    item: "Checklist item",
    removeItem: "Remove checklist item",
    save: "Save task",
    cancel: "Cancel",
    delete: "Delete task",
    deleteConfirm: "Delete this task and its checklist?",
    move: "Move task",
    moveUp: "Move up",
    noTasks: "No tasks here yet.",
    loading: "Loading…",
    retry: "Try again",
    saved: "Saved",
    saving: "Saving…",
    failed: "Could not save. Your changes are still here; please try again.",
    loadFailed: "Could not load your subjects.",
    conflict:
      "This board changed in another tab or device. Load the latest version before continuing.",
    reload: "Load latest version",
    full: "This subject has reached the limit of 100 tasks. Delete a finished task to add another.",
    discard: "Discard your unsaved changes?",
    unsaved: "Unsaved changes",
    open: "My notes & tasks",
    overdue: "Overdue",
    boardHint: "Drag cards to move them, or use each card’s status menu.",
  },
  cs: {
    subjects: "Předměty",
    intro: "Vlastní prostor pro poznámky a úkoly ke každému předmětu.",
    private: "Tyto poznámky a úkoly vidíte jen vy, i když sdílíte svůj rozvrh.",
    subject: "Předmět",
    empty:
      "Zatím tu nejsou žádné předměty. Načtěte rozvrh nebo přidejte vlastní předmět.",
    notes: "Poznámky",
    notesHint: "Poznámky z přednášek, užitečné odkazy nebo co si zapamatovat…",
    saveNotes: "Uložit poznámky",
    tasks: "Úkoly",
    todo: "K vyřízení",
    doing: "Rozpracované",
    done: "Hotové",
    add: "Přidat úkol",
    edit: "Upravit úkol",
    title: "Název úkolu",
    description: "Popis",
    due: "Termín",
    checklist: "Seznam kroků",
    addItem: "Přidat krok",
    item: "Krok",
    removeItem: "Odebrat krok",
    save: "Uložit úkol",
    cancel: "Zrušit",
    delete: "Smazat úkol",
    deleteConfirm: "Smazat tento úkol včetně seznamu kroků?",
    move: "Přesunout úkol",
    moveUp: "Posunout výš",
    noTasks: "Zatím žádné úkoly.",
    loading: "Načítání…",
    retry: "Zkusit znovu",
    saved: "Uloženo",
    saving: "Ukládání…",
    failed:
      "Uložení se nezdařilo. Změny zůstaly ve formuláři; zkuste to znovu.",
    loadFailed: "Předměty se nepodařilo načíst.",
    conflict:
      "Nástěnka se změnila v jiném okně nebo zařízení. Nejdříve načtěte nejnovější verzi.",
    reload: "Načíst nejnovější verzi",
    full: "Tento předmět dosáhl limitu 100 úkolů. Pro přidání dalšího smažte některý hotový úkol.",
    discard: "Zahodit neuložené změny?",
    unsaved: "Neuložené změny",
    open: "Moje poznámky a úkoly",
    overdue: "Po termínu",
    boardHint:
      "Karty můžete přetahovat nebo změnit jejich stav pomocí nabídky.",
  },
  uk: {
    subjects: "Предмети",
    intro: "Власний простір для нотаток і завдань до кожного предмета.",
    private:
      "Ці нотатки й завдання бачите лише ви, навіть коли ділитеся розкладом.",
    subject: "Предмет",
    empty: "Предметів ще немає. Оновіть розклад або додайте власний предмет.",
    notes: "Нотатки",
    notesHint: "Нотатки з лекцій, корисні посилання чи нагадування…",
    saveNotes: "Зберегти нотатки",
    tasks: "Завдання",
    todo: "До виконання",
    doing: "У процесі",
    done: "Виконано",
    add: "Додати завдання",
    edit: "Редагувати завдання",
    title: "Назва завдання",
    description: "Опис",
    due: "Термін",
    checklist: "Список кроків",
    addItem: "Додати крок",
    item: "Крок",
    removeItem: "Видалити крок",
    save: "Зберегти завдання",
    cancel: "Скасувати",
    delete: "Видалити завдання",
    deleteConfirm: "Видалити це завдання разом зі списком кроків?",
    move: "Перемістити завдання",
    moveUp: "Перемістити вище",
    noTasks: "Тут ще немає завдань.",
    loading: "Завантаження…",
    retry: "Спробувати ще раз",
    saved: "Збережено",
    saving: "Збереження…",
    failed: "Не вдалося зберегти. Зміни залишились у формі; спробуйте ще раз.",
    loadFailed: "Не вдалося завантажити предмети.",
    conflict:
      "Дошка змінилася в іншій вкладці або на іншому пристрої. Спочатку завантажте останню версію.",
    reload: "Завантажити останню версію",
    full: "Досягнуто ліміт у 100 завдань. Видаліть виконане завдання, щоб додати нове.",
    discard: "Відхилити незбережені зміни?",
    unsaved: "Незбережені зміни",
    open: "Мої нотатки й завдання",
    overdue: "Прострочено",
    boardHint: "Перетягуйте картки або змінюйте їхній стан через меню.",
  },
};
